### ISSUE TITLE
Register exported IModules as a Module

### ISSUE THREAD

**Issue by IngoVals** [autofac/Autofac.Mef#3]
When I export IModules in MEF I would expect them to be registered as Modules in Autofac.

This could be the default handling of IModules or a new extension method. I can see the usefulness in plugging in Modules instead of just components.

**Comment by tillig** [comment]
It'd probably be better to just register your modules directly with Autofac rather than export them and assume they'll be handled differently than _every other type getting exported_. If we wanted to do what you're describing, we'd have to add a special case just for that type and handle just that type differently... and that assumes the dev actually wants that to happen and didn't intentionally export modules for a different purpose.

It also provides a potential chicken/egg problem where we have to resolve exports from catalogs and things that may not be entirely built or ready to be resolved. What if the exported module has an importing constructor? Uh oh.

If you can solve this one, we'd be happy to accept a pull request; otherwise, I think we'll probably not be implementing this. Sorry.
