### ISSUE TITLE
ASP.NET Core RC2

### ISSUE THREAD

**Issue by dazinator** [autofac/Autofac.Mef#7]
I have tried to use this in an ASP.NET Core RC2 application today, are there any plans to update this NuGet package to work for RC2?

I think it requires that it be compatible with NET 452..

**Comment by tillig** [comment]
To the best of my knowledge, they haven't updated MEF for .NET Core support. While the [Microsoft.Composition](https://www.nuget.org/packages/Microsoft.Composition/) (or "MEF 2") package exists, I recall trying to port to that and finding there was a pretty substantial difference in behavior and a lot of missing types due to the trimming down they did for MEF 2.

We don't currently have plans to port to MEF 2. If we did, it'd probably have to be a separate/new package because things in MEF 2 are so different.
