### ISSUE TITLE
Cannot resolve Meta dependencies within Export class

### ISSUE THREAD

**Issue by alex-zyl** [autofac/Autofac.Mef#8]
I have a class **TestClass** decorated with [Export] attribute implementations and public interface IJob that have multiple implementations that are decorated with [MetadataAttribute] and [ExportAttribute]

I'm trying to import all possible implementation into **TestClass**.
This is what I get when resolving TestClass instance from Autofac container:

```csharp
[Export(typeof(ITestClass))]
public class TestClass : ITestClass
{
    //Found 11 implementations
    [ImportMany]
    private IEnumerable<IJob> jobs4;

    // Found 0 
    [ImportMany]
    private IEnumerable<ExportFactory<IJob>> jobs;

    // Found 0 
    [ImportMany]
    private IEnumerable<ExportFactory<IJob, INameMetadata>> jobs2;

    // Found 0 
    [ImportMany]
    private IEnumerable<Meta<Func<IJob>>> jobs3;
}
```

Same happens when using ctor injection.

However, when I go to container and directly try to resolve IEnumerable<Meta<Func<IJob>>> I gell all available implementations.
Is this a bug or I'm doing something wrong?

**Comment by tillig** [comment]
Can you provide your whole repro so we can see what's going on?

Note that there's actually a pretty good chance you're not doing anything wrong and instead are just trying to do something the package doesn't support. `Autofac.Mef` does a pretty good job of trying to bring MEF stuff into Autofac, but it's not two-way (it doesn't get Autofac into MEF) and it's not 100% full-featured (e.g., I'm not sure what `ExportFactory<T>` is but that's not something we've coded to support).

**Comment by alex-zyl** [comment]
Here's the simple project
```
class Program
    {
        static void Main(string[] args)
        {
            var builder = new ContainerBuilder();
            builder.RegisterComposablePartCatalog(new ApplicationCatalog());

            var container = builder.Build();

            var instance = container.Resolve<IResolver>();

        }
    }

    [Export(typeof(IResolver))]
    public class Resolver : IResolver
    {
        [ImportMany]
        private IEnumerable<ExportFactory<IJob>> jobs;

        [ImportMany]
        private IEnumerable<Meta<Func<IJob>>> jobs3;

        [ImportMany]
        private IEnumerable<IJob> jobs4;
    }

    public interface IResolver { }

    [AttributeUsage(AttributeTargets.Class)]
    [MetadataAttribute]
    [PartCreationPolicy(CreationPolicy.NonShared)]
    public class JobNameAttribute : ExportAttribute
    {
        public JobNameAttribute(string name) : base(typeof(IJob))
        {
            Name = name;
        }

        public string Name { get; private set; }
    }

    public interface IJob { }

    [JobName("Simple")]
    public class SimpleJob : IJob
    { }

    [JobName("Complex")]
    public class ComplexJob : IJob
    { }
```

So idea is to get the list of IJob factories inside of Resolver.

**Comment by tillig** [comment]
Cool, thanks. **I won't lie, it may be a bit before we can get to this.**

Something to consider if you're in more of a hurry is [to look at our troubleshooting docs](http://autofac.readthedocs.io/en/latest/advanced/debugging.html) on setting up the SymbolSource and MyGet symbol servers and debug into the library. MEF integration is pretty complicated because MEF does some pretty crazy things.

Places I'd look...

- Do you need to [add `builder.RegisterMetadataRegistrationSources()`](http://autofac.readthedocs.io/en/latest/advanced/metadata.html) to get the attribute metadata working?
- If you [set a breakpoint on this line where the metadata for an export definition is registered](https://github.com/autofac/Autofac.Mef/blob/115850568d4792ff68dfdc332832610596a65d75/src/Autofac.Integration.Mef/RegistrationExtensions.cs#L418), is the metadata you're expecting actually there?
- If you make things `public` instead of `private` does it make a difference? Generally Autofac doesn't work on private members. Try actually filling out the `IResolver` interface with real properties and implement public properties on the `Resolver` class.
- Does it change if you register a `TypeCatalog` with the specific types rather than an `ApplicationCatalog`? It shouldn't for something like this, but just in case...

Hope that at least gets you started.

**Comment by alex-zyl** [comment]
@tillig  Thanks for the reply

ExportFactory<T> is just a way to dynamically create objects at runtime. 
so `ExportFactory<T>` (in MEF) == `Func<T>` (in Autofac)

1. Private fields\properties work for Autofac as well and upon running th demo I got dependencies injected into this field.

```
   [ImportMany]
   private IEnumerable<IJob> jobs4;
```
Changing field to public and making it property didn't solve the issue. Still getting empty collections for 
`IEnumerable<Meta<Func<IJob>>>` and `IEnumerable<ExportFactory<IJob>>`

2. RegisterMetadataRegistrationSources made possible to resolve dependencies using `<Meta<Func<IJob>, INameMetadata>` construction. Without this, metadata is  still available from Meta.Metadata dictionary. 

3. Registering Resolver, SimpleJob and ComplexJob types in TypeCatalog doesn't fix the issue as well.

**Comment by alex-zyl** [comment]
@tillig  
Seems that Mef extension is not capable of resolving Meta or ExportFactory entities.
When declaring `IEnumerable<Meta<T>>` import, Mef doesn't recognize `Meta<T>` and can't find any implementation of this. So it seems that we cannot combine Mef and Autofac injections. 

Things could be much easier if `ReflectionParameterImportDefinition` derived types were public. 
So taking into account this issue https://github.com/autofac/Autofac/issues/326, it won't be fixed.

**Comment by tillig** [comment]
Given the MEF integration is more "get MEF into Autofac" and not "get Autofac into MEF" it makes sense now that you mention it why `Meta<T>` doesn't work.

> [MEF integration allows Autofac to resolve items that were registered in MEF, but it doesn’t allow MEF to resolve items that were registered in Autofac.](http://autofac.readthedocs.io/en/latest/integration/mef.html)

As you noted, I'm not sure we can address the other issues, either - `ExportFactory<T>` for example. This may just have to be documented as a known shortcoming. Does that sound about right?
